=== ceviksuleyman/Log4jTestNG/src/test/java/testData/PhysicianJsonSchema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$ref": "#/definitions/Welcome2",
  "definitions": {
    "Welcome2": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "createdBy": {
          "type": "string"
        },
        "createdDate": {
          "type": "string",
          "format": "date-time"
        },
        "id": {
          "type": "integer"
        },
        "firstName": {
          "type": "string"
        },
        "lastName": {
          "type": "string"
        },
        "birthDate": {
          "type": "string",
          "format": "date-time"
        },
        "phone": {
          "type": "string"
        },
        "gender": {
          "type": "string"
        },
        "bloodGroup": {
          "type": "string"
        },
        "adress": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "user": {
          "$ref": "#/definitions/User"
        },
        "speciality": {
          "type": "string"
        },
        "appointments": {
          "type": "null"
        },
        "country": {
          "$ref": "#/definitions/Country"
        },
        "cstate": {
          "$ref": "#/definitions/Cstate"
        },
        "examFee": {
          "type": "number"
        },
        "image": {
          "type": "null"
        },
        "imageContentType": {
          "type": "null"
        }
      },
      "required": [
        "adress",
        "appointments",
        "birthDate",
        "bloodGroup",
        "country",
        "createdBy",
        "createdDate",
        "cstate",
        "description",
        "examFee",
        "firstName",
        "gender",
        "id",
        "image",
        "imageContentType",
        "lastName",
        "phone",
        "speciality",
        "user"
      ],
      "title": "Welcome2"
    },
    "Country": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "name"
      ],
      "title": "Country"
    },
    "Cstate": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "country": {
          "$ref": "#/definitions/Country"
        }
      },
      "required": [
        "country",
        "id",
        "name"
      ],
      "title": "Cstate"
    },
    "User": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "createdBy": {
          "type": "string"
        },
        "createdDate": {
          "type": "string",
          "format": "date-time"
        },
        "id": {
          "type": "integer"
        },
        "login": {
          "type": "string"
        },
        "firstName": {
          "type": "string"
        },
        "lastName": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "activated": {
          "type": "boolean"
        },
        "langKey": {
          "type": "string"
        },
        "imageUrl": {
          "type": "null"
        },
        "resetDate": {
          "type": "null"
        },
        "ssn": {
          "type": "string"
        }
      },
      "required": [
        "activated",
        "createdBy",
        "createdDate",
        "email",
        "firstName",
        "id",
        "imageUrl",
        "langKey",
        "lastName",
        "login",
        "resetDate",
        "ssn"
      ],
      "title": "User"
    }
  }
}

=== ceviksuleyman/Log4jTestNG/src/test/java/testData/Physician.json
{
  "createdBy": "cevik",
  "createdDate": "2022-11-18T16:03:39.976299Z",
  "id": 309705,
  "firstName": "Doktor",
  "lastName": "Team16",
  "birthDate": "2002-03-11T22:00:00Z",
  "phone": "999-343-4343",
  "gender": "MALE",
  "bloodGroup": "Apositive",
  "adress": "Papua Yeni Gine",
  "description": "team16hasta",
  "user": {
    "createdBy": "anonymousUser",
    "createdDate": "2022-11-16T10:19:40.206848Z",
    "id": 302609,
    "login": "doktorteam16",
    "firstName": "Doktor",
    "lastName": "Team16",
    "email": "doktorteam16@gmail.com",
    "activated": true,
    "langKey": "en",
    "imageUrl": null,
    "resetDate": null,
    "ssn": "123-65-2365"
  },
  "speciality": "ALLERGY_IMMUNOLOGY",
  "appointments": null,
  "country": {
    "id": 71230,
    "name": "Gambia"
  },
  "cstate": {
    "id": 1262,
    "name": "Hawaii",
    "country": {
      "id": 1201,
      "name": ""
    }
  },
  "examFee": 1200.00,
  "image": null,
  "imageContentType": null
}
